export const environment = {
  production: true,
  'InsertUrl': 'https://medplusapi.herokuapp.com/MedPlus/user',
  'LoginUrl': 'https://medplusapi.herokuapp.com/MedPlus/login',
  'searchProductURL': 'https://medplusapi.herokuapp.com/MedPlus/productsearch',
  'orderhistoryURL': 'https://medplusapi.herokuapp.com/MedPlus/orderhistory',
  'buyProductURL': 'https://medplusapi.herokuapp.com/MedPlus/buynow',
  'loadCartURL': 'https://medplusapi.herokuapp.com/MedPlus/checkout',
  'deletecartitemURL': 'https://medplusapi.herokuapp.com/MedPlus/deletecartitem',
  'loadUser': 'https://medplusapi.herokuapp.com/MedPlus/user',
  // 'orderUpdate': 'https://medplusapi.herokuapp.com/MedPlus/orderupdate',
  'orderUpdate': 'https://medplusapi.herokuapp.com/MedPlus/orderupdate',
  'getProductUrl': 'https://medplusapi.herokuapp.com/MedPlus/product/',
  'insertIntoCartURL': 'https://medplusapi.herokuapp.com/MedPlus/cart',
  'getUserbyMailURL': 'https://medplusapi.herokuapp.com/MedPlus/email/',
  'postReviewbyProductURL': 'https://medplusapi.herokuapp.com/MedPlus/review',
  'getProductbyProductURL': 'https://medplusapi.herokuapp.com/MedPlus/product/2/',
  'getProductCategoryURL': 'https://medplusapi.herokuapp.com/MedPlus/product/category/',
  'deleteOrderHistoryURL': 'https://medplusapi.herokuapp.com/MedPlus/deletehistory/'
};
